### ISSUE TITLE
Name cannot be null

### ISSUE THREAD

**Issue by TNTUP** [PlanetCraft/MobArena#3]
```
[18:17:11 INFO]: [MobArena] Enabling MobArena v1.0.0-SNAPSHOT
[18:17:11 INFO]: [MobArena] Vault found; economy rewards enabled.
[18:17:11 ERROR]: Error occurred while enabling MobArena v1.0.0-SNAPSHOT (Is it up to date?)
java.lang.IllegalArgumentException: Name cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.getWorld(CraftServer.java:1020) ~[spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
        at org.bukkit.Bukkit.getWorld(Bukkit.java:500) ~[spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
        at com.garbagemule.MobArena.ArenaImpl.<init>(ArenaImpl.java:189) ~[?:?]
        at com.garbagemule.MobArena.ArenaMasterImpl.loadArena(ArenaMasterImpl.java:578) ~[?:?]
        at com.garbagemule.MobArena.ArenaMasterImpl.loadArenasInWorld(ArenaMasterImpl.java:535) ~[?:?]
        at com.garbagemule.MobArena.ArenaMasterImpl.loadArenas(ArenaMasterImpl.java:519) ~[?:?]
        at com.garbagemule.MobArena.ArenaMasterImpl.initialize(ArenaMasterImpl.java:238) ~[?:?]
        at com.garbagemule.MobArena.MobArena.onEnable(MobArena.java:93) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:363) [PlugMan.jar:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) [PlugMan.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:647) [spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:633) [spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437) [spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-16c940b-f15e07b]
```
testing on spigot 1.11. Tried regenerating new config, same problem :(

**Comment by markhughes** [comment]
I'm not currently maintaining this fork

**Comment by TNTUP** [comment]
Aw :/ I was interested with those signs, nevermind then. The official one works. Thanks though

**Comment by markhughes** [comment]
I may pick it up in the future again, we will see. :)

**Comment by markhughes** [comment]
Having a go at replicating and fixing this soon.

**Comment by mibby** [comment]
Bump. Any update? :)
