### ISSUE TITLE
IllegalArgumentException: Name cannot be null

### ISSUE THREAD

**Issue by mibby** [PlanetCraft/MobArena#5]
Compiled source as of commit https://github.com/PlanetCraft/MobArena/commit/36313d5b2f90eafacce14d88b4b4ef46bcdd81da
PaperSpigot dev 933 (MC 1.11)
https://ci.destroystokyo.com/

Error occurs on start-up when trying to load. :(

```
[23:26:20 INFO]: [MobArena] Enabling MobArena v1.0.0-SNAPSHOT
[23:26:20 INFO]: [MobArena] Vault found; economy rewards enabled.
[23:26:20 ERROR]: Error occurred while enabling MobArena v1.0.0-SNAPSHOT (Is it up to date?)
java.lang.IllegalArgumentException: Name cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.11.jar:git-Paper-933]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.getWorld(CraftServer.java:1058) ~[patched_1.11.jar:git-Paper-933]
        at org.bukkit.Bukkit.getWorld(Bukkit.java:518) ~[patched_1.11.jar:git-Paper-933]
        at com.garbagemule.MobArena.ArenaImpl.<init>(ArenaImpl.java:189) ~[?:?]
        at com.garbagemule.MobArena.ArenaMasterImpl.loadArena(ArenaMasterImpl.java:577) ~[?:?]
        at com.garbagemule.MobArena.ArenaMasterImpl.loadArenasInWorld(ArenaMasterImpl.java:535) ~[?:?]
        at com.garbagemule.MobArena.ArenaMasterImpl.loadArenas(ArenaMasterImpl.java:519) ~[?:?]
        at com.garbagemule.MobArena.ArenaMasterImpl.initialize(ArenaMasterImpl.java:238) ~[?:?]
        at com.garbagemule.MobArena.MobArena.onEnable(MobArena.java:93) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.jar:git-Paper-933]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.jar:git-Paper-933]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.jar:git-Paper-933]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:377) [patched_1.11.jar:git-Paper-933]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:327) [patched_1.11.jar:git-Paper-933]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:433) [patched_1.11.jar:git-Paper-933]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:394) [patched_1.11.jar:git-Paper-933]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:332) [patched_1.11.jar:git-Paper-933]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.jar:git-Paper-933]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:599) [patched_1.11.jar:git-Paper-933]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
[23:26:20 INFO]: [MobArena] Disabling MobArena v1.0.0-SNAPSHOT
[23:26:20 INFO]: [MobArena] disabled.
```

**Comment by markhughes** [comment]
This looks like issue #3 - I'll open it, and fix it.
